# Generated by Django 5.0.4 on 2024-04-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventEco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sympla_event_id', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('private_event', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
