# Generated by Django 5.0.4 on 2024-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventeco',
            name='category_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventeco',
            name='host_name',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
