# Generated by Django 5.0.4 on 2024-04-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitriao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('order_updated_date', models.DateTimeField()),
                ('order_approved_date', models.DateTimeField(blank=True, null=True)),
                ('order_discount', models.CharField(max_length=255)),
                ('ticket_number', models.CharField(max_length=255)),
                ('ticket_num_qr_code', models.CharField(max_length=255)),
                ('ticket_name', models.CharField(max_length=255)),
                ('pdv_user', models.CharField(max_length=255)),
                ('ticket_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
