# Generated by Django 5.0.4 on 2024-04-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_anfitriao_categoria_cliente_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiSympla',
            new_name='Api',
        ),
    ]
